### ISSUE TITLE
lock command not working on xubuntu

### ISSUE THREAD

**Issue by aviram83** [the-cavalry/light-locker#73]
I have try to run the command:

$ light-locker-command -l

but nothing happen

spec:
lightdm 1.16.6
xubuntu 15.10
light-locker-command 1.6.0

**Comment by ochosi** [comment]
What you mention here suggests that light-locker isn't really running, otherwise the light-locker-command would do something.
Do you find light-locker in the running processes? (e.g. "ps -A | grep light-locker")

**Comment by aviram83** [comment]
You are right!

I have done uninstall and reinstall and it work, that you.

I guess I have assume this should be run with the install of xubuntu

**Comment by rapgro** [comment]
You should report this installation failure to your maintainer of the (x)ubuntu package as a downstream bug with packaging as such. We do not see any such issue with the Fedora package.

**Comment by ochosi** [comment]
@aviram83: Well usually it does autostart with Xubuntu, I can't say what would have disabled it (may also depend on how you installed/upgraded to 15.10 or maybe you changed a setting in xfce4-power-manager or light-locker-settings and just don't remember?)...

Anyway, closing this issue, since it's a non-issue ;)
