### ISSUE TITLE
Session lost after locking the screen and re-logging in with LightDM

### ISSUE THREAD

**Issue by heartofalion** [the-cavalry/light-locker#84]
When I lock the screen in Xfce using light-locker and then try to unlock the screen again by logging back in with LightDM, then the session is lost and it's like the computer has freshly rebooted.

I've posted extensively with more details about this issue in this forum thread:

https://forum.manjaro.org/t/manjaro-forgets-its-session-after-locking-the-screen-lightdm-light-locker-issue/7873/14

**Comment by NicoHood** [comment]
I also have this problem on Arch with xfce4. However it might be a little different still.

Sometimes my keyboard etc is all not recognized after trying to login again. Sometimes it helps to disconnect my laptop from the docking station, however this is not always possible, if I've mounted harddisk drives. It also happened a few times that my X session then crashes. However this is only sometimes - playing with fire.

**Comment by Upgreydd** [comment]
confirmed +1

**Comment by cavalier38** [comment]
Light-locker can't restart the session. As the forum says, it is more likely LightDM or one of the other services.

**Comment by NicoHood** [comment]
@cavalier38 how about my described issue?

**Comment by cavalier38** [comment]
I missed that. It might be hard to find the cause as it only happens sometimes.
To me that also sounds like Xorg or VT switching related (which is done by LightDM).
In order to truly exclude light-locker, would be to disable light-locker but still lock the session, with dm-tool for example. If it still happens, it isn't caused by light-locker. And light-locker probably won't be able to solve it either.

If you believe it is a light-locker problem, feel free to open a new issue as the symptoms seem to be different.
